GET http://localhost:3000/api/users/1/secret
########
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "jaber.d03@htlwienwest.at",
    "password": "1234"
}
###########
GET http://localhost:3000/api/login/